Tracking the current session in time
PWA-Summit/2021.pwasummit.org pull request #23
Opened 2021-09-01 18:05 UTC by aarongustafson

There is a bit of code you can change to test on Line 117.

2021-09-01 20:24 UTC, Snugug requested changes
Hey Aaron,

Thanks for doing this! Overall the code looks good, my comments are mostly nit picking, so if you'd prefer not to do them to get this merged just LMK and I'll approve. The only one that's less nit-picky is moving the JS to a separate file so our linting can properly run against it (simple as `<script type="module">import './js/schedule.js"</script>` or something like that to bring it in; no need to futz around with getting it into the head or the footer)

2021-09-01 20:24 UTC, Snugug commented on src/index.njk
> +<script>
Can we move this out to a JS file and `import` it so we can run things like linting, prettier, and minimization over it?

2021-09-01 20:24 UTC, Snugug commented on src/index.njk
> +    var $sessions = [].slice.call(document.querySelectorAll('tr[data-starts][data-ends]'));
Instead of casting this to an array, can we just keep it as a NodeList and use `for…of` over it instead of `forEach` later on?

2021-09-01 20:24 UTC, Snugug commented on src/index.njk
> +        console.log(now, start, end);
```suggestion
```

2021-09-01 20:24 UTC, Snugug commented on src/index.njk
> +          $session.removeAttribute('aria-current');
Love the use of `aria-current` and that the styling selector is built off of it too

2021-09-01 20:24 UTC, Snugug commented on src/index.njk
> +  (function (window, document) {
I'm not super worried about a wrapping closure for this, especially if it gets moved to a module and imported

2021-09-01 20:24 UTC, Snugug commented on src/index.njk
> +          end = Date.parse($session.dataset.ends);
My preference in general is to use `let/const` instead of `var`, which I think is probably OK as I don't think our target demographic for this conference includes people whose browsers don't support it. Either way, I do have a somewhat strong preference to not create multiple variables using commas like this; I think it makes code harder to follow

2021-09-01 20:24 UTC, Snugug commented on src/index.njk
> +      $sessions.forEach(function ($session) {
I generally prefer `for…of` to `forEach` as it doesn't create a new function context and is generally faster.

2021-09-01 20:24 UTC, Snugug commented on src/index.njk
> +        updateSchedule();
This is more of a nit than anything, but because we're already getting the date here, why not pass in the value of `getTime` instead of calling `Date.now` in `updateSchedule`? I guess it doesn't really make a difference, but in theory makes `updateSchedule` more testable?

2021-09-01 20:24 UTC, Snugug commented on src/index.njk
> +        aria-label="Choose a timezone"
Thanks for adding this; sorry I forgot it to begin with

2021-09-02 16:48 UTC, aarongustafson commented on src/index.njk
> +    var $sessions = [].slice.call(document.querySelectorAll('tr[data-starts][data-ends]'));
Yeah, we can. My original pass used filter to find the current ont, but then I remembered I needed to hit every node to toggle.

2021-09-02 17:12 UTC, aarongustafson commented on src/index.njk
> +<script>
@Snugug Would it make sense to move this code into the existing Schedule class?

2021-09-02 17:56 UTC, aarongustafson commented on src/index.njk
> +    <tr data-even="{{even}}" data-starts="{{session.startsAt}}" data-ends="{{session.endsAt}}">
I was using Date.parse() which seems to be fine with the API data, but I added a Date enforcement bit similar to your code. Let me know if you think I need more guardrails.

2021-09-02 18:08 UTC, aarongustafson commented
Refactored. Let me know what you think.

2021-09-02 18:11 UTC, Snugug approved these changes

2021-09-02 18:11 UTC, Snugug commented
TYVM for the refactor! Looks good to me!

2021-09-02 18:11 UTC, merged