Add YT embed
PWA-Summit/2021.pwasummit.org pull request #27
Opened 2021-09-27 19:47 UTC by Snugug

Add livestream embed to site!

2021-09-27 20:29 UTC, aarongustafson requested changes
LGTM apart from the `@supports` block :-)

2021-09-27 20:29 UTC, aarongustafson commented on src/sass/components/_livestream.scss
> +  @supports not (aspect-ratio: 16 / 9) {
If `@supports` is not supported, this block will be ignored. Shouldn’t this be the default and then undone within the `@supports` block that follows?

2021-09-27 21:01 UTC, Snugug commented on src/sass/components/_livestream.scss
> +  @supports not (aspect-ratio: 16 / 9) {
While I'd normally agree, our overall website support is a subset of CSS supports support, so I think including that is fine

2021-09-30 15:21 UTC, aarongustafson approved these changes

2021-09-30 15:21 UTC, merged