Cfp
PWA-Summit/2021.pwasummit.org pull request #4
Opened 2021-06-07 21:22 UTC by Snugug

Add landing page an Code of Conduct

2021-06-08 21:09 UTC, webmaxru requested changes

2021-06-09 10:22 UTC, Snugug commented on vite.config.js
> +        background_color: '#108484',
I'm not sure I understand this comment? `color` isn't a manifest property and, [per the spec](https://w3c.github.io/manifest/#background_color-member), is meant to describe the expected background color of the site (which currently is this teal) to provide a smooth transition to that background color when the PWA window loads..

2021-06-09 10:26 UTC, Snugug commented on vite.config.js
> +        name: 'PWA Summit',
Thanks for pointing out that the plugin adds a `short_name` here that we probably don't want. I think in our case, having the short name and long name be the same is the better choice so I'm going to do that, as the `name` property is meant to be how the app is typically displayed to users (like in application lists or as icon labels) and serves as the accessible name, so we shouldn't overload it with descriptive information.

2021-06-09 17:31 UTC, webmaxru commented on vite.config.js
> +        name: 'PWA Summit',
For me, it's better to have `name` a bit more descriptive than `short_name` (it exists in spec to provide a _full_ name for the app/project) but it's not a big deal for this initial version so I approve your version.

2021-06-09 17:41 UTC, webmaxru commented on vite.config.js
> +        background_color: '#108484',
Thanks for the fix - yes, for sure I meant `theme_color `. And either from the false memory or from some early specs I thought that the splashscreen will contain app `name` printed using `theme_color` on the `background_color`. But I see that now it's one of the `icons` on the `background_color`.

2021-06-09 17:42 UTC, webmaxru requested changes

2021-06-09 17:42 UTC, webmaxru commented on templates/_layouts/wrapper.njk
> +            <strong>Samsung</strong>, <strong>Intel</strong>
Name to be updated to Samsung Internet
```suggestion
            <strong>Samsung Internet</strong>, <strong>Intel</strong>
```

2021-06-10 21:09 UTC, webmaxru approved these changes

2021-06-10 21:09 UTC, merged